spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauthtest
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yml